# 수정된 docker-compose.yml
version: '3.8'
services:
  app:
    env_file:
      - .env
    image: ${DOCKER_HUB_USERNAME}/eye-on:${IMAGE_TAG:-latest}
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - /var/log/eye-on:/app/logs
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s