# 수정된 docker-compose.yml
services:
  app:
    env_file:
      - .env
    image: ${DOCKER_HUB_USR}/${APP_NAME}:${IMAGE_TAG}
    container_name: ${CONTAINER_NAME}
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - /var/log/eye-on:/app/logs
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge