version: '3.8'
services:
  app:
    env_file:
      - .env
    environment:
      - DB_URL=jdbc:postgresql://host.docker.internal:5432/${DB_NAME}
      - REDIS_HOST=host.docker.internal
    build: .
    container_name: ${CONTAINER_NAME}
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - /var/log/eye-on:/app/logs
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
    mem_swappiness: 0
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s
    networks:
      - monitoring
      - default

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    privileged: true
    restart: unless-stopped
    container_name: cadvisor
    ports:
      - "8085:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:v2.43.0
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --web.console.templates=/etc/prometheus/consoles
      - --web.enable-lifecycle
      - --web.enable-remote-write-receiver
    depends_on:
      - cadvisor
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    restart: unless-stopped
    ports:
      - "4000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    depends_on:
      - prometheus
    networks:
      - monitoring

  k6:
    image: grafana/k6:0.47.0
    container_name: k6
    ports:
      - "6565:6565"
    command: [ "sleep", "infinity" ]
    environment:
      - K6_PROMETHEUS_RW_SERVER_URL=http://prometheus:9090/api/v1/write
      - K6_OUT=experimental-prometheus-rw
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
    volumes:
      - ./src/test/java/com/on/eye/api/performance/scripts:/scripts
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - prometheus
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"
    depends_on:
      - prometheus
    networks:
      - monitoring



networks:
  monitoring:

volumes:
  postgres-data:
  prometheus-data:
  grafana-storage:
