server:
  tomcat:
    mbeanregistry:
      enabled: true
  servlet:
    context-path: /api             # 컨텍스트 패스는 별도로 설정
spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: api
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: ${KAKAO_CLIENT_ID}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "${BASE_URL}/api/login/oauth2/code/kakao"
            scope:
              - profile_nickname
              - profile_image
        #              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  datasource:
    hikari:
      driver-class-name: org.postgresql.Driver
      connection-timeout: '20000'
      maximum-pool-size: '4'
      minimum-idle: '1'
      connection-test-query: SELECT 1
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    url: ${DB_URL}

  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: '100'
    open-in-view: false
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: 'false'
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migrations
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      # connection timeout
      connect-timeout: 30s
      # read timeout
      timeout: 10s
auth:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration: 360000000 # 100 day
    refresh-expiration: 604800000 # 1 week
app:
  oauth2:
    redirectUri: "${FRONT_BASE_URL}/oauth2/callback"

hash:
  secret-key: ${HASH_SECRET_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  prometheus:
    metrics:
      export:
        enabled: true
  info:
    process:
      enabled: true

logging:
  config: classpath:log4j2-${spring.profiles.active}.xml
  level:
    web: DEBUG
    com.zaxxer.hikari.HikariConfig: DEBUG
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG
    org.springframework.security.web.authentication.OAuth2LoginAuthenticationFilter: TRACE