spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    hikari:
      driver-class-name: org.postgresql.Driver
      connection-timeout: '20000'
      maximum-pool-size: '10'
      connection-test-query: SELECT 1
      minimum-idle: '5'
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    url: ${DB_URL}
  application:
    name: api
  jpa:
    show-sql: 'true'
    properties:
      hibernate:
        format_sql: 'true'
        use_sql_comments: 'true'
        default_batch_fetch_size: '100'
    open-in-view: false
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: 'true'

logging:
  level:
    web: DEBUG
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG